import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, HeartPulse, Plus, Trash2, UserRound } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { getToken } from "@/auth/token";
import { getEstablishmentWorkspace, getManagedResident, updateManagedResident, type EstablishmentResident, type EstablishmentWorkspace } from "@/api/establishments";
import { getActiveCarePlan, saveCarePlan, supportLevelLabels, taskCategoryLabels, taskFrequencyLabels, type CarePlan, type CarePlanSupportLevel, type SaveCarePlanInput } from "@/api/carePlans";
import { Button, Card, ErrorState, Input, PageHeader, Select, Skeleton, Textarea, useToast } from "@/components/ui";

type ResidentStatus = "active" | "archived";
const emptyPlan:SaveCarePlanInput={supportLevel:"LOW",goals:[],instructions:[],precautions:[],tasks:[]};
function recordText(value?:Record<string,unknown>){if(!value)return "";return Object.entries(value).map(([key,v])=>`${key}: ${String(v)}`).join("\n");}
function textRecord(value:string){const result:Record<string,unknown>={};for(const line of value.split("\n").map(v=>v.trim()).filter(Boolean)){const i=line.indexOf(":");if(i>0)result[line.slice(0,i).trim()]=line.slice(i+1).trim();else result[line]=true;}return result;}
const lines=(value:string)=>value.split("\n").map(v=>v.trim()).filter(Boolean);

export function EstablishmentResidentProfilePage(){
 const{establishmentId="",residentId=""}=useParams();const{activeOrganization}=useAuth();const navigate=useNavigate();const toast=useToast();
 const[workspace,setWorkspace]=useState<EstablishmentWorkspace|null>(null);const[resident,setResident]=useState<EstablishmentResident|null>(null);const[carePlan,setCarePlan]=useState<CarePlan|null>(null);const[error,setError]=useState(false);const[editing,setEditing]=useState(false);const[editingPlan,setEditingPlan]=useState(false);const[saving,setSaving]=useState(false);
 const[form,setForm]=useState({firstName:"",lastName:"",preferredName:"",dateOfBirth:"",allergies:"",preferences:"",routines:"",status:"active" as ResidentStatus});
 const[planForm,setPlanForm]=useState({supportLevel:"LOW" as CarePlanSupportLevel,goals:"",instructions:"",precautions:"",tasks:emptyPlan.tasks});
 const load=useCallback(async()=>{const token=getToken();if(!token||!activeOrganization?.id||!establishmentId)return;try{const[w,r,p]=await Promise.all([getEstablishmentWorkspace(activeOrganization.id,establishmentId,token),getManagedResident(activeOrganization.id,establishmentId,residentId,token),getActiveCarePlan(activeOrganization.id,residentId,token)]);setWorkspace(w);setResident(r.resident);setCarePlan(p);setError(false);}catch{setError(true);}},[activeOrganization?.id,establishmentId,residentId]);useEffect(()=>{void load();},[load]);
 if(error)return <ErrorState kind="server" onRetry={()=>void load()}/>;if(!workspace||!resident)return <Skeleton className="h-40"/>;
 const openEdit=()=>{setForm({firstName:resident.first_name??"",lastName:resident.last_name??"",preferredName:resident.preferred_name??"",dateOfBirth:resident.date_of_birth??"",allergies:resident.allergies?.join(", ")??"",preferences:recordText(resident.preferences),routines:recordText(resident.routines),status:(resident.status as ResidentStatus)||"active"});setEditing(true);};
 const save=async()=>{const token=getToken();if(!token||!activeOrganization?.id||!form.firstName.trim()||!form.lastName.trim())return;setSaving(true);try{const response=await updateManagedResident(activeOrganization.id,establishmentId,residentId,{firstName:form.firstName.trim(),lastName:form.lastName.trim(),preferredName:form.preferredName.trim()||null,dateOfBirth:form.dateOfBirth||null,allergies:form.allergies.split(",").map(v=>v.trim()).filter(Boolean),preferences:textRecord(form.preferences),routines:textRecord(form.routines),status:form.status},token);setResident(response.resident);setEditing(false);toast.show("Expediente del residente actualizado.","success");}catch{toast.show("No pudimos actualizar el expediente.","danger");}finally{setSaving(false);}};
 const openPlan=()=>{const p=carePlan?.plan_details;setPlanForm({supportLevel:p?.supportLevel??"LOW",goals:p?.goals.join("\n")??"",instructions:p?.instructions.join("\n")??"",precautions:p?.precautions.join("\n")??"",tasks:p?.tasks.map(t=>({...t}))??[]});setEditingPlan(true);};
 const addTask=()=>setPlanForm(v=>({...v,tasks:[...v.tasks,{title:"",details:"",category:"OTHER",frequency:"DAILY",priority:"ROUTINE",requiresConfirmation:true}]}));
 const savePlan=async()=>{const token=getToken();if(!token||!activeOrganization?.id)return;setSaving(true);try{const saved=await saveCarePlan(activeOrganization.id,residentId,{supportLevel:planForm.supportLevel,goals:lines(planForm.goals),instructions:lines(planForm.instructions),precautions:lines(planForm.precautions),tasks:planForm.tasks.filter(t=>t.title.trim()).map(t=>({...t,title:t.title.trim()}))},token);setCarePlan(saved);setEditingPlan(false);toast.show("Plan de cuidado guardado. Se creó una nueva versión.","success");}catch{toast.show("No pudimos guardar el plan de cuidado.","danger");}finally{setSaving(false);}};
 return <div className="flex flex-col gap-5"><button onClick={()=>navigate(`/caregiver/admin/establishments/${establishmentId}`)} className="flex items-center gap-2"><ArrowLeft size={17}/>Volver a {workspace.establishment.name}</button><PageHeader title={`${resident.first_name} ${resident.last_name}`} description={`Expediente operacional · ${workspace.establishment.name}`} actions={!editing?<Button onClick={openEdit}>Editar expediente</Button>:undefined}/>
 {editing?<Card className="flex flex-col gap-3"><div className="flex items-center gap-2"><UserRound size={20}/><b>Editar expediente</b></div><Input label="Nombre" value={form.firstName} onChange={e=>setForm(v=>({...v,firstName:e.target.value}))}/><Input label="Apellidos" value={form.lastName} onChange={e=>setForm(v=>({...v,lastName:e.target.value}))}/><Input label="Nombre preferido" value={form.preferredName} onChange={e=>setForm(v=>({...v,preferredName:e.target.value}))}/><Input label="Fecha de nacimiento" type="date" value={form.dateOfBirth} onChange={e=>setForm(v=>({...v,dateOfBirth:e.target.value}))}/><Input label="Alergias (separadas por coma)" value={form.allergies} onChange={e=>setForm(v=>({...v,allergies:e.target.value}))}/><Textarea label="Preferencias" value={form.preferences} onChange={e=>setForm(v=>({...v,preferences:e.target.value}))}/><Textarea label="Rutinas" value={form.routines} onChange={e=>setForm(v=>({...v,routines:e.target.value}))}/><Select label="Estado" value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value as ResidentStatus}))}><option value="active">Activo</option><option value="archived">Archivado</option></Select><div className="flex gap-2"><Button onClick={()=>void save()} disabled={saving}>{saving?"Guardando…":"Guardar cambios"}</Button><Button variant="secondary" onClick={()=>setEditing(false)}>Cancelar</Button></div></Card>:<div className="grid gap-3 md:grid-cols-2"><Card><div className="flex items-center gap-2 mb-3"><UserRound size={20}/><b>Información básica</b></div><p>Nombre legal: {resident.first_name} {resident.last_name}</p><p>Nombre preferido: {resident.preferred_name||"No registrado"}</p><p>Fecha de nacimiento: {resident.date_of_birth||"No registrada"}</p><p>Habitación: {resident.room_id||"No asignada"}</p><p>Estado: {resident.status}</p></Card><Card><div className="flex items-center gap-2 mb-3"><HeartPulse size={20}/><b>Información de cuidado</b></div><p>Alergias: {resident.allergies?.length?resident.allergies.join(", "):"No registradas"}</p><p className="mt-2"><b>Preferencias</b></p><pre className="whitespace-pre-wrap font-sans text-sm">{recordText(resident.preferences)||"No registradas"}</pre><p className="mt-2"><b>Rutinas</b></p><pre className="whitespace-pre-wrap font-sans text-sm">{recordText(resident.routines)||"No registradas"}</pre></Card></div>}
 <Card className="flex flex-col gap-4"><div className="flex items-center justify-between gap-3"><div><b>Plan individual de cuidado</b><p className="text-sm text-[var(--color-text-muted)]">{carePlan?`Versión ${carePlan.version} · ${supportLevelLabels[carePlan.plan_details.supportLevel]}`:"Aún no hay un plan activo."}</p></div>{!editingPlan&&<Button onClick={openPlan}>{carePlan?"Editar plan":"Crear plan"}</Button>}</div>
 {editingPlan?<div className="flex flex-col gap-3"><Select label="Nivel de apoyo" value={planForm.supportLevel} onChange={e=>setPlanForm(v=>({...v,supportLevel:e.target.value as CarePlanSupportLevel}))}>{Object.entries(supportLevelLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Textarea label="Objetivos (uno por línea)" value={planForm.goals} onChange={e=>setPlanForm(v=>({...v,goals:e.target.value}))}/><Textarea label="Instrucciones (una por línea)" value={planForm.instructions} onChange={e=>setPlanForm(v=>({...v,instructions:e.target.value}))}/><Textarea label="Precauciones (una por línea)" value={planForm.precautions} onChange={e=>setPlanForm(v=>({...v,precautions:e.target.value}))}/><div className="flex items-center justify-between"><b>Tareas</b><Button variant="secondary" onClick={addTask}><Plus size={16}/> Añadir tarea</Button></div>{planForm.tasks.map((task,i)=><Card key={task.id??i} className="flex flex-col gap-2"><Input label="Tarea" value={task.title} onChange={e=>setPlanForm(v=>({...v,tasks:v.tasks.map((t,x)=>x===i?{...t,title:e.target.value}:t)}))}/><Input label="Detalles" value={task.details??""} onChange={e=>setPlanForm(v=>({...v,tasks:v.tasks.map((t,x)=>x===i?{...t,details:e.target.value}:t)}))}/><div className="grid gap-2 md:grid-cols-2"><Select label="Categoría" value={task.category} onChange={e=>setPlanForm(v=>({...v,tasks:v.tasks.map((t,x)=>x===i?{...t,category:e.target.value as typeof t.category}:t)}))}>{Object.entries(taskCategoryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Select label="Frecuencia" value={task.frequency} onChange={e=>setPlanForm(v=>({...v,tasks:v.tasks.map((t,x)=>x===i?{...t,frequency:e.target.value as typeof t.frequency}:t)}))}>{Object.entries(taskFrequencyLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></div><Button variant="secondary" onClick={()=>setPlanForm(v=>({...v,tasks:v.tasks.filter((_,x)=>x!==i)}))}><Trash2 size={16}/> Quitar tarea</Button></Card>)}<div className="flex gap-2"><Button onClick={()=>void savePlan()} disabled={saving}>{saving?"Guardando…":"Guardar plan"}</Button><Button variant="secondary" onClick={()=>setEditingPlan(false)}>Cancelar</Button></div></div>:carePlan&&<div><p><b>Objetivos:</b> {carePlan.plan_details.goals.join(" · ")||"No registrados"}</p><p><b>Instrucciones:</b> {carePlan.plan_details.instructions.join(" · ")||"No registradas"}</p><p><b>Precauciones:</b> {carePlan.plan_details.precautions.join(" · ")||"No registradas"}</p><div className="mt-3"><b>Tareas ({carePlan.plan_details.tasks.length})</b>{carePlan.plan_details.tasks.map(t=><div key={t.id} className="mt-2 rounded-lg border p-3"><p className="font-medium">{t.title}</p><p className="text-sm">{taskCategoryLabels[t.category]} · {taskFrequencyLabels[t.frequency]} · {t.priority}</p>{t.details&&<p className="text-sm mt-1">{t.details}</p>}</div>)}</div></div>}</Card></div>;
}
