import { useEffect,useMemo,useState,type FormEvent } from "react";
import { CheckCircle2,KeyRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { activateOrganizationAdminInvitation,inspectOrganizationAdminInvitation,type OrganizationAdminInvitationInspection } from "@/api/platformOrganizations";
import { Button,Card,Input,Skeleton } from "@/components/ui";

export function OrganizationAdminInvitationPage(){
 const navigate=useNavigate();
 const token=useMemo(()=>new URLSearchParams(window.location.search).get("token")??"",[]);
 const[invitation,setInvitation]=useState<OrganizationAdminInvitationInspection|null|undefined>(token?undefined:null);
 const[password,setPassword]=useState("");const[confirmation,setConfirmation]=useState("");const[submitting,setSubmitting]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState<string|null>(token?null:"El enlace de invitación no es válido.");
 useEffect(()=>{if(!token)return;inspectOrganizationAdminInvitation(token).then(setInvitation).catch(()=>{setInvitation(null);setError("Esta invitación venció, ya fue utilizada o fue revocada.");});},[token]);
 async function submit(e:FormEvent){e.preventDefault();if(!invitation)return;setError(null);if(invitation.account_exists){setError("Ya existe una cuenta con este correo. Inicia sesión con esa cuenta para completar el acceso.");return;}if(password!==confirmation){setError("Las contraseñas no coinciden.");return;}setSubmitting(true);try{await activateOrganizationAdminInvitation(token,password);setDone(true);window.history.replaceState(null,"",window.location.pathname);}catch{setError("No pudimos activar la cuenta. Solicita una invitación nueva si este enlace ya fue utilizado o venció.");}finally{setSubmitting(false);}}
 if(invitation===undefined&&!error)return <div className="min-h-dvh flex items-center justify-center bg-[var(--color-navy-950)] px-[var(--spacing-md)]"><Skeleton className="w-full max-w-[440px] h-80"/></div>;
 return <div className="min-h-dvh flex items-center justify-center bg-[var(--color-navy-950)] px-[var(--spacing-md)] py-8"><Card className="w-full max-w-[440px] flex flex-col gap-5"><div className="text-center">{done?<CheckCircle2 size={42} className="mx-auto text-[var(--color-success-600)]"/>:<KeyRound size={38} className="mx-auto text-[var(--color-navy-700)]"/>}<h1 className="font-display text-[var(--text-h1)] text-[var(--color-text-primary)] mt-3">{done?"Cuenta de administrador creada":"Crear cuenta de administrador"}</h1>{invitation&&!done&&<p className="text-[var(--text-small)] text-[var(--color-text-secondary)] mt-2">Has sido invitado a administrar <strong>{invitation.organization_name}</strong>.</p>}</div>{done?<><p className="text-center text-[var(--text-small)] text-[var(--color-text-secondary)]">Tu cuenta quedó vinculada únicamente a la organización que te invitó.</p><Button fullWidth onClick={()=>navigate("/login",{replace:true})}>Iniciar sesión</Button></>:invitation?<form className="flex flex-col gap-4" onSubmit={submit}><div className="rounded-[var(--radius-md)] bg-[var(--color-ivory-100)] p-3 text-[var(--text-small)] text-[var(--color-text-secondary)]">Correo invitado: <strong>{invitation.email_masked}</strong><br/>Organización: <strong>{invitation.organization_name}</strong><br/>Vence: {new Date(invitation.expires_at).toLocaleString("es-PR")}</div>{invitation.account_exists?<p role="alert" className="text-[var(--text-small)] text-[var(--color-danger-700)]">Ya existe una cuenta con este correo. Por seguridad, no cambiaremos su contraseña desde una invitación.</p>:<><Input label="Crea una contraseña" type="password" autoComplete="new-password" hint="Usa al menos 12 caracteres." minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required/><Input label="Confirma la contraseña" type="password" autoComplete="new-password" minLength={12} maxLength={128} value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/></>}{error&&<p role="alert" className="text-[var(--text-small)] text-[var(--color-danger-700)]">{error}</p>}<Button type="submit" size="lg" fullWidth loading={submitting} disabled={invitation.account_exists}>Crear mi cuenta</Button>{invitation.account_exists&&<Button type="button" variant="secondary" fullWidth onClick={()=>navigate("/login")}>Ir al inicio de sesión</Button>}</form>:<><p role="alert" className="text-center text-[var(--text-small)] text-[var(--color-danger-700)]">{error}</p><Button variant="secondary" fullWidth onClick={()=>navigate("/login")}>Volver al inicio de sesión</Button></>}</Card></div>;
}
