import { useCallback,useEffect,useState } from "react";
import { DollarSign, RefreshCw } from "lucide-react";
import { useAuth } from "@/auth/AuthProvider"; import { getToken } from "@/auth/token";
import { listFinancialRates,listTimesheets,reviewTimesheet,saveFinancialRate,type FinancialRate,type Timesheet,type TimesheetSummary } from "@/api/timesheets";
import { Button,Card,PageHeader } from "@/components/ui";
const date=(d:Date)=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const usd=(c:number|null)=>c==null?"—":new Intl.NumberFormat("es-PR",{style:"currency",currency:"USD"}).format(c/100);
export function AgencyTimesheetsPage(){const {activeOrganization}=useAuth();const now=new Date(),past=new Date();past.setDate(now.getDate()-14);
const [from,setFrom]=useState(date(past)),[to,setTo]=useState(date(now)),[status,setStatus]=useState(""),[rows,setRows]=useState<Timesheet[]>([]),[rates,setRates]=useState<FinancialRate[]>([]),[summary,setSummary]=useState<TimesheetSummary|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
const load=useCallback(async()=>{const token=getToken(),org=activeOrganization?.id;if(!token||!org)return;setLoading(true);setError("");try{const [t,r]=await Promise.all([listTimesheets(org,from,to,status,token),listFinancialRates(org,token)]);setRows(t.timesheets);setSummary(t.summary);setRates(r)}catch{setError("No se pudieron cargar las horas y tarifas.")}finally{setLoading(false)}},[activeOrganization?.id,from,to,status]);
useEffect(()=>{void load()},[load]);
async function approve(t:Timesheet){const token=getToken(),org=activeOrganization?.id;if(!token||!org)return;const raw=prompt("Minutos a aprobar",String(t.recorded_minutes));if(raw===null)return;const m=Number(raw);let note: string|undefined;if(m!==t.recorded_minutes){note=prompt("Explique el ajuste")||undefined;if(!note)return}await reviewTimesheet(org,t.id,"approved",token,m,note);await load()}
async function dispute(t:Timesheet){const token=getToken(),org=activeOrganization?.id;if(!token||!org)return;const note=prompt("Motivo de la disputa");if(!note)return;await reviewTimesheet(org,t.id,"disputed",token,undefined,note);await load()}
async function rate(r:FinancialRate){const token=getToken(),org=activeOrganization?.id;if(!token||!org)return;const p=prompt("Pago por hora (USD)",r.pay_rate_cents==null?"":String(r.pay_rate_cents/100)),b=p===null?null:prompt("Tarifa a facturar por hora (USD)",r.bill_rate_cents==null?"":String(r.bill_rate_cents/100));if(p===null||b===null)return;await saveFinancialRate(org,r.membership_id,Math.round(Number(p)*100),Math.round(Number(b)*100),token);await load()}
return <div className="flex flex-col gap-[var(--spacing-lg)]"><PageHeader title="Horas y facturación" description="Revisa horas reales y prepara nómina y facturación. ETNARA no mueve dinero ni emite pagos." actions={<Button variant="secondary" icon={<RefreshCw size={18}/>} onClick={()=>void load()} loading={loading}>Actualizar</Button>}/>
<div className="flex flex-wrap gap-3"><label>Desde <input className="border rounded p-2" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta <input className="border rounded p-2" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><select className="border rounded p-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="pending">Pendiente</option><option value="approved">Aprobado</option><option value="disputed">Disputado</option></select></div>
{error&&<Card><p className="text-red-700">{error}</p></Card>}{summary&&<div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Card>Registrado<br/><b>{(summary.recordedMinutes/60).toFixed(2)} h</b></Card><Card>Aprobado<br/><b>{(summary.approvedMinutes/60).toFixed(2)} h</b></Card><Card>Pago preparado<br/><b>{usd(summary.approvedPayCents)}</b></Card><Card>Facturación preparada<br/><b>{usd(summary.approvedBillCents)}</b></Card></div>}
<Card><h2 className="font-display text-lg mb-3">Hojas de tiempo</h2>{rows.length===0?<p>Sin hojas de tiempo en este periodo.</p>:<div className="flex flex-col gap-3">{rows.map(t=><div key={t.id} className="border-b pb-3"><b>{t.worker_name||"Cuidador"}</b> · {t.recipient_name||"Sin residente"} · {(t.recorded_minutes/60).toFixed(2)} h · {t.status}<div className="mt-2">{t.status!=="approved"&&<><Button onClick={()=>void approve(t)}>Aprobar</Button> <Button variant="secondary" onClick={()=>void dispute(t)}>Disputar</Button></>}</div></div>)}</div>}</Card>
<Card><h2 className="font-display text-lg mb-1 flex items-center gap-2"><DollarSign size={18}/>Tarifas del equipo</h2><p className="text-sm mb-3">Visible solo en Agencia; no se expone a Familia ni al cuidador.</p>{rates.map(r=><div key={r.membership_id} className="flex justify-between items-center border-b py-3"><span><b>{r.display_name||"Cuidador"}</b><br/><small>Pago {usd(r.pay_rate_cents)}/h · Facturación {usd(r.bill_rate_cents)}/h</small></span><Button variant="secondary" onClick={()=>void rate(r)}>Editar</Button></div>)}</Card></div>}
