import { useCallback,useEffect,useState } from "react";
import { DollarSign,RefreshCw,LockKeyhole } from "lucide-react";
import { useAuth } from "@/auth/AuthProvider"; import { getToken } from "@/auth/token";
import { closePayPeriod,listFinancialRates,listPayPeriods,listTimesheets,previewPayPeriod,reviewTimesheet,saveFinancialRate,type FinancialRate,type PayPeriod,type PayPeriodPreview,type Timesheet,type TimesheetSummary } from "@/api/timesheets";
import { Button,Card,PageHeader } from "@/components/ui";
const date=(d:Date)=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const usd=(c:number|null)=>c==null?"—":new Intl.NumberFormat("es-PR",{style:"currency",currency:"USD"}).format(c/100);
function localPreview(rows:Timesheet[],from:string,to:string,cadence:string):PayPeriodPreview{const approved=rows.filter(x=>x.status==="approved"),map=new Map<string,{workerName:string;approvedMinutes:number;payAmountCents:number;billAmountCents:number;timesheets:number}>();for(const x of approved){const k=x.worker_name||"Cuidador",a=map.get(k)||{workerName:k,approvedMinutes:0,payAmountCents:0,billAmountCents:0,timesheets:0};a.approvedMinutes+=Number(x.approved_minutes||0);a.payAmountCents+=Number(x.pay_amount_cents||0);a.billAmountCents+=Number(x.bill_amount_cents||0);a.timesheets++;map.set(k,a)}return{dateFrom:from,dateTo:to,cadence:cadence as PayPeriodPreview["cadence"],workers:[...map.values()],exceptions:{pending:rows.filter(x=>x.status==="pending").length,disputed:rows.filter(x=>x.status==="disputed").length},summary:{approvedMinutes:approved.reduce((s,x)=>s+Number(x.approved_minutes||0),0),payAmountCents:approved.reduce((s,x)=>s+Number(x.pay_amount_cents||0),0),billAmountCents:approved.reduce((s,x)=>s+Number(x.bill_amount_cents||0),0),approvedTimesheets:approved.length}}}
export function AgencyTimesheetsPage(){const {activeOrganization}=useAuth();const now=new Date(),past=new Date();past.setDate(now.getDate()-14);
const [from,setFrom]=useState(date(past)),[to,setTo]=useState(date(now)),[status,setStatus]=useState(""),[cadence,setCadence]=useState("biweekly"),[rows,setRows]=useState<Timesheet[]>([]),[rates,setRates]=useState<FinancialRate[]>([]),[summary,setSummary]=useState<TimesheetSummary|null>(null),[preview,setPreview]=useState<PayPeriodPreview|null>(null),[periods,setPeriods]=useState<PayPeriod[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[periodApiWarning,setPeriodApiWarning]=useState(false);
const load=useCallback(async()=>{const token=getToken(),org=activeOrganization?.id;if(!token||!org)return;setLoading(true);setError("");setPeriodApiWarning(false);try{const [t,r]=await Promise.all([listTimesheets(org,from,to,status,token),listFinancialRates(org,token)]);setRows(t.timesheets);setSummary(t.summary);setRates(r);setPreview(localPreview(t.timesheets,from,to,cadence));const [p,h]=await Promise.allSettled([previewPayPeriod(org,from,to,cadence,token),listPayPeriods(org,token)]);if(p.status==="fulfilled"&&p.value)setPreview(p.value);else setPeriodApiWarning(true);if(h.status==="fulfilled")setPeriods(h.value);else setPeriodApiWarning(true)}catch{setError("No se pudieron cargar las horas o tarifas.")}finally{setLoading(false)}},[activeOrganization?.id,from,to,status,cadence]);
useEffect(()=>{void load()},[load]);
async function approve(t:Timesheet){const token=getToken(),org=activeOrganization?.id;if(!token||!org)return;const raw=prompt("Minutos a aprobar",String(t.recorded_minutes));if(raw===null)return;const m=Number(raw);let note: string|undefined;if(m!==t.recorded_minutes){note=prompt("Explique el ajuste")||undefined;if(!note)return}await reviewTimesheet(org,t.id,"approved",token,m,note);await load()}
async function dispute(t:Timesheet){const token=getToken(),org=activeOrganization?.id;if(!token||!org)return;const note=prompt("Motivo de la disputa");if(!note)return;await reviewTimesheet(org,t.id,"disputed",token,undefined,note);await load()}
async function rate(r:FinancialRate){const token=getToken(),org=activeOrganization?.id;if(!token||!org)return;const p=prompt("Pago por hora (USD)",r.pay_rate_cents==null?"":String(r.pay_rate_cents/100)),b=p===null?null:prompt("Tarifa a facturar por hora (USD)",r.bill_rate_cents==null?"":String(r.bill_rate_cents/100));if(p===null||b===null)return;await saveFinancialRate(org,r.membership_id,Math.round(Number(p)*100),Math.round(Number(b)*100),token);await load()}
async function closePeriod(){const token=getToken(),org=activeOrganization?.id;if(!token||!org||!preview)return;if(preview.exceptions.pending||preview.exceptions.disputed){alert("Resuelve las hojas pendientes o disputadas antes de cerrar el periodo.");return}if(!confirm(`Cerrar el periodo ${from} al ${to}? Después quedará registrado como cerrado.`))return;try{await closePayPeriod(org,from,to,cadence,token);await load()}catch{alert("No se pudo cerrar el periodo en el servidor. Verifica que el Backend 7.9 esté desplegado y que no existan excepciones.")}}
function exportCsv(){if(!preview)return;const lines=[["Cuidador","Horas aprobadas","Pago preparado","Facturación preparada","Hojas"],...preview.workers.map(w=>[w.workerName,(w.approvedMinutes/60).toFixed(2),(w.payAmountCents/100).toFixed(2),(w.billAmountCents/100).toFixed(2),String(w.timesheets)])];const blob=new Blob([lines.map(x=>x.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`etnara-periodo-${from}-${to}.csv`;a.click();URL.revokeObjectURL(a.href)}
return <div className="flex flex-col gap-[var(--spacing-lg)]"><PageHeader title="Horas y facturación" description="Revisa horas reales, prepara nómina y facturación y cierra periodos. ETNARA no mueve dinero ni emite pagos." actions={<Button variant="secondary" icon={<RefreshCw size={18}/>} onClick={()=>void load()} loading={loading}>Actualizar</Button>}/>
<div className="flex flex-wrap gap-3"><label>Desde <input className="border rounded p-2" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta <input className="border rounded p-2" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><select className="border rounded p-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="pending">Pendiente</option><option value="approved">Aprobado</option><option value="disputed">Disputado</option></select></div>
{error&&<Card><p className="text-red-700">{error}</p></Card>}{summary&&<div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Card>Registrado<br/><b>{(summary.recordedMinutes/60).toFixed(2)} h</b></Card><Card>Aprobado<br/><b>{(summary.approvedMinutes/60).toFixed(2)} h</b></Card><Card>Pago preparado<br/><b>{usd(summary.approvedPayCents)}</b></Card><Card>Facturación preparada<br/><b>{usd(summary.approvedBillCents)}</b></Card></div>}
{preview&&<Card><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-display text-lg">Cierre del periodo</h2><p className="text-sm">Agrupa las horas aprobadas antes de preparar payroll/contabilidad.</p></div><select className="border rounded p-2" value={cadence} onChange={e=>setCadence(e.target.value)}><option value="weekly">Semanal</option><option value="biweekly">Quincenal</option><option value="custom">Personalizado</option></select></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 my-4"><div>Horas aprobadas<br/><b>{(preview.summary.approvedMinutes/60).toFixed(2)} h</b></div><div>Pago<br/><b>{usd(preview.summary.payAmountCents)}</b></div><div>Facturación<br/><b>{usd(preview.summary.billAmountCents)}</b></div><div>Excepciones<br/><b>{preview.exceptions.pending+preview.exceptions.disputed}</b></div></div>{preview.workers.map(w=><div key={w.workerName} className="border-t py-3"><b>{w.workerName}</b> · {(w.approvedMinutes/60).toFixed(2)} h · Pago {usd(w.payAmountCents)} · Facturación {usd(w.billAmountCents)}</div>)}<div className="flex flex-wrap gap-2 mt-3"><Button icon={<LockKeyhole size={17}/>} onClick={()=>void closePeriod()} disabled={preview.exceptions.pending+preview.exceptions.disputed>0}>Cerrar periodo</Button><Button variant="secondary" onClick={exportCsv}>Exportar CSV</Button></div>{preview.exceptions.pending+preview.exceptions.disputed>0&&<p className="text-sm mt-2">Antes de cerrar: {preview.exceptions.pending} pendiente(s) y {preview.exceptions.disputed} disputada(s).</p>}{periodApiWarning&&<p className="text-sm mt-2">El resumen está disponible; el historial/cierre del servidor se está sincronizando.</p>}</Card>}
<Card><h2 className="font-display text-lg mb-3">Periodos cerrados</h2>{periods.length===0?<p className="text-sm">Todavía no hay periodos cerrados.</p>:periods.map(p=><div key={p.id} className="border-b py-3"><b>{p.date_from} — {p.date_to}</b> · {(p.approved_minutes/60).toFixed(2)} h · {usd(p.pay_amount_cents)} pago · {usd(p.bill_amount_cents)} facturación · Cerrado</div>)}</Card>
<Card><h2 className="font-display text-lg mb-3">Hojas de tiempo</h2>{rows.length===0?<p>Sin hojas de tiempo en este periodo.</p>:<div className="flex flex-col gap-3">{rows.map(t=><div key={t.id} className="border-b pb-3"><b>{t.worker_name||"Cuidador"}</b> · {t.recipient_name||"Sin residente"} · {(t.recorded_minutes/60).toFixed(2)} h · {t.status}<div className="mt-2">{t.status!=="approved"&&<><Button onClick={()=>void approve(t)}>Aprobar</Button> <Button variant="secondary" onClick={()=>void dispute(t)}>Disputar</Button></>}</div></div>)}</div>}</Card>
<Card><h2 className="font-display text-lg mb-1 flex items-center gap-2"><DollarSign size={18}/>Tarifas del equipo</h2><p className="text-sm mb-3">Visible solo en Agencia; no se expone a Familia ni al cuidador.</p>{rates.map(r=><div key={r.membership_id} className="flex justify-between items-center border-b py-3"><span><b>{r.display_name||"Cuidador"}</b><br/><small>Pago {usd(r.pay_rate_cents)}/h · Facturación {usd(r.bill_rate_cents)}/h</small></span><Button variant="secondary" onClick={()=>void rate(r)}>Editar</Button></div>)}</Card></div>}
