import { useCallback,useEffect,useState } from "react";
import { Building2,Plus,RefreshCw } from "lucide-react";
import { getToken } from "@/auth/token";
import { createPlatformOrganization,listPlatformOrganizations,type PlatformOrganization,type PlatformOrganizationType } from "@/api/platformOrganizations";
import { Button,Card,EmptyState,ErrorState,Input,Modal,PageHeader,Skeleton,useToast } from "@/components/ui";

export function PlatformOrganizationsPage(){
 const[organizations,setOrganizations]=useState<PlatformOrganization[]|null>(null);const[error,setError]=useState(false);const[open,setOpen]=useState(false);const[name,setName]=useState("");const[type,setType]=useState<PlatformOrganizationType>("agency");const[saving,setSaving]=useState(false);const toast=useToast();
 const load=useCallback(async()=>{const token=getToken();if(!token)return;setError(false);try{setOrganizations(await listPlatformOrganizations(token));}catch{setError(true);}},[]);useEffect(()=>{void load();},[load]);
 async function create(){if(!name.trim()){toast.show("Escribe el nombre de la organización.","warning");return;}const token=getToken();if(!token)return;setSaving(true);try{await createPlatformOrganization({name:name.trim(),type},token);toast.show("Organización creada.","success");setOpen(false);setName("");setType("agency");await load();}catch{toast.show("No pudimos crear la organización.","danger");}finally{setSaving(false);}}
 return <div className="space-y-[var(--spacing-md)]"><PageHeader title="Organizaciones" description="Clientes B2B independientes de ETNARA. Cada organización mantiene separados su personal, residentes, documentos, cumplimiento y operaciones." actions={<div className="flex gap-2"><Button variant="secondary" icon={<RefreshCw size={17}/>} onClick={()=>void load()}>Actualizar</Button><Button icon={<Plus size={17}/>} onClick={()=>setOpen(true)}>Nueva organización</Button></div>}/>
 {organizations===null&&!error?<Skeleton className="h-48"/>:error?<Card><ErrorState kind="server" onRetry={()=>void load()}/></Card>:organizations.length===0?<Card><EmptyState icon={<Building2 size={30}/>} title="No hay organizaciones" description="Crea la primera agencia o establecimiento cliente de ETNARA."/></Card>:<div className="grid gap-3 md:grid-cols-2">{organizations.map(o=><Card key={o.id}><div className="flex items-start gap-3"><Building2 size={22}/><div><h2 className="font-display text-[var(--text-h3)]">{o.name}</h2><p className="text-[var(--text-small)] text-[var(--color-text-secondary)]">{o.type==="agency"?"Agencia de cuidado":"Hogar / establecimiento residencial"} · {o.status}</p><p className="mt-2 text-[var(--text-caption)] text-[var(--color-text-muted)]">ID: {o.id}</p></div></div></Card>)}</div>}
 <Modal open={open} onClose={()=>!saving&&setOpen(false)} title="Nueva organización" footer={<><Button variant="secondary" disabled={saving} onClick={()=>setOpen(false)}>Cancelar</Button><Button loading={saving} onClick={()=>void create()}>Crear organización</Button></>}><div className="space-y-4"><Input label="Nombre de la organización" value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. ETNARA Test — Agencia B" maxLength={160}/><label className="block text-[var(--text-small)] font-medium">Tipo<select className="mt-1 w-full rounded-[var(--radius-md)] border border-[var(--color-border)] bg-white p-3" value={type} onChange={e=>setType(e.target.value as PlatformOrganizationType)}><option value="agency">Agencia de cuidado</option><option value="residential_establishment">Hogar / establecimiento residencial</option></select></label><p className="text-[var(--text-small)] text-[var(--color-text-secondary)]">La organización se crea como un cliente separado. Sus datos no se comparten con otras organizaciones.</p></div></Modal></div>;
}
