/** Cliente HTTP mínimo para el backend real de ETNARA. */
export interface ApiError { status:number; code?:string; message?:string; isNetworkError?:boolean; }
function apiBase():string{const raw=import.meta.env.VITE_API_URL;if(!raw){const err:ApiError={status:0,message:"VITE_API_URL no está configurada."};throw err;}return raw.replace(/\/+$/,"");}
function buildUrl(path:string):string{const normalized=path.startsWith("/")?path:`/${path}`;return `${apiBase()}${normalized}`;}
async function parseJsonSafely(response:Response):Promise<unknown>{const text=await response.text();if(!text)return null;try{return JSON.parse(text);}catch{return null;}}
interface RequestOptions{method:"GET"|"POST"|"PUT"|"PATCH"|"DELETE";body?:unknown;token?:string|null;}
async function postBinary<T>(path:string,body:Blob,contentType:string,token:string):Promise<T>{let response:Response;try{response=await fetch(buildUrl(path),{method:"POST",headers:{"Content-Type":contentType,Authorization:`Bearer ${token}`},body});}catch{throw {status:0,isNetworkError:true} as ApiError;}const responseBody=await parseJsonSafely(response);if(!response.ok){const code=responseBody&&typeof responseBody==="object"&&"error" in responseBody&&typeof(responseBody as {error:unknown}).error==="string"?(responseBody as {error:string}).error:undefined;throw {status:response.status,code} as ApiError;}return responseBody as T;}
async function request<T>(path:string,options:RequestOptions):Promise<T>{const headers:Record<string,string>={"Content-Type":"application/json"};if(options.token)headers.Authorization=`Bearer ${options.token}`;let response:Response;try{response=await fetch(buildUrl(path),{method:options.method,headers,body:options.body!==undefined?JSON.stringify(options.body):undefined});}catch{throw {status:0,isNetworkError:true} as ApiError;}const body=await parseJsonSafely(response);if(!response.ok){const code=body&&typeof body==="object"&&"error" in body&&typeof(body as {error:unknown}).error==="string"?(body as {error:string}).error:undefined;throw {status:response.status,code} as ApiError;}return body as T;}
export const apiClient={get:<T>(path:string,token?:string|null)=>request<T>(path,{method:"GET",token}),post:<T>(path:string,body?:unknown,token?:string|null)=>request<T>(path,{method:"POST",body,token}),put:<T>(path:string,body?:unknown,token?:string|null)=>request<T>(path,{method:"PUT",body,token}),patch:<T>(path:string,body?:unknown,token?:string|null)=>request<T>(path,{method:"PATCH",body,token}),delete:<T>(path:string,token?:string|null)=>request<T>(path,{method:"DELETE",token}),postBinary};
